# Generated by Django 3.2.9 on 2021-11-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('CompanyId', models.AutoField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('DateOfJoining', models.DateField()),
                ('Post', models.CharField(max_length=25)),
                ('vacancy', models.IntegerField()),
            ],
        ),
    ]
