# Generated by Django 3.2.9 on 2021-11-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='offcampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('Date', models.DateTimeField()),
                ('Post', models.CharField(max_length=25)),
                ('vacancy', models.IntegerField()),
                ('Package', models.IntegerField()),
            ],
        ),
    ]
