# Generated by Django 3.2.9 on 2021-11-08 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offcampus',
            name='Time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offcampus',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='offcampus',
            name='Package',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='offcampus',
            name='companyname',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
