# Generated by Django 3.2.9 on 2021-11-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211108_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offcampus',
            name='Time',
        ),
        migrations.AlterField(
            model_name='offcampus',
            name='Date',
            field=models.DateField(),
        ),
    ]
