# Generated by Django 3.2.9 on 2021-11-08 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211108_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='offcampus',
            name='Time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
